system = "x86_64-linux"

[config]
publicKey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKW2RBUkd9iB3Gs2Krxi9aB3XZE78Qd3RPvA8emXtCpD"
syncthingDeviceID = "ZL2OU7Q-IRYWF7H-VNX6A65-RHWQXIF-AK2G22Y-KB43E2U-DAMNCFP-66IWKQX"

profiles = [
  "profiles/hardware/usbcore",
  "profiles/hardware/x570",
  "profiles/default_fs",
  "profiles/desktop",
  "profiles/greetd",
  "profiles/hidpi",
  "profiles/home-manager",
  "profiles/homedns",
  "profiles/interception-tools",
  "profiles/pcscd",
  "profiles/state",
  "profiles/syncthing",
  "profiles/tailscale",
  "profiles/zram",
]

[config.programs.mosh]
enable = true

[config.virtualisation.libvirtd]
enable = true

[config.boot.binfmt]
emulatedSystems = [ "aarch64-linux" ]

[config.boot.initrd.luks.devices]
cryptkey.keyFile = "/dev/disk/by-partlabel/alt_key"
cryptkey.fallbackToPassword = true

[config.environment.state."/keep"]
directories = [
  "/var/lib/libvirt",
]

[config.age.secrets]
spotnix = { file = "secrets/spotnix.age", owner = "1337" }
spotifyd = { file = "secrets/spotifyd.age", owner = "1337" }
wifi-networks.file = "secrets/wifi-networks.age"
wg-home.file = "secrets/eris/wg-home.age"
wg-net.file = "secrets/eris/wg-net.age"
id_ed25519_agenda_updater = { file = "secrets/id_ed25519_agenda_updater.age", owner = "1337" }
id_ed25519_roam_updater = { file = "secrets/id_ed25519_roam_updater.age", owner = "1337" }
id_ed25519_bbph = { file = "secrets/id_ed25519_bbph.age", owner = "1337", path = "/home/john/.ssh/id_ed25519_bbph" }
id_ed25519_alt = { file = "secrets/id_ed25519_alt.age", owner = "1337", path = "/home/john/.ssh/id_ed25519_alt" }
syncthing-cert = { file = "secrets/eris/syncthing-cert.age", owner = "1337" }
syncthing-key = { file = "secrets/eris/syncthing-key.age", owner = "1337" }
mbsync-insane = { file = "secrets/mbsync-insane.age", owner = "1337" }
mbsync-9000 = { file = "secrets/mbsync-9000.age", owner = "1337" }
authinfo = { file = "secrets/authinfo.age", owner = "1337", path = "/home/john/.authinfo" }

[config.services.syncthing]
enable = true
devices.SM-G998B.id = "PCFNIXF-AR7YX2B-354IJQW-YP25QM7-N53ES5L-HKB337S-I6JZV34-55LQEAR"
user = "john"
group = "users"
openDefaultPorts = true
folders."/home/john/Sync".id = "sync"
folders."/home/john/Sync".devices = [
  "triton",
  "polaris",
  "icarus",
  "titan",
  "hyperion"
]
folders."/home/john/Photos".id = "sm-g998b_7dxn foton"
folders."/home/john/Photos".devices = [
  "triton",
  "polaris",
  "icarus",
  "SM-G998B"
]
folders."/home/john/Photos".versioning.type = "staggered"
folders."/home/john/Photos".versioning.params.cleanInterval = "3600"
folders."/home/john/Photos".versioning.params.maxAge = "0"
folders."/home/john/Photos".versioning.params.versionsPath = "/home/john/Photos/stbackup"

cert = "/run/agenix/syncthing-cert"
key = "/run/agenix/syncthing-key"
dataDir = "/home/john/.local/share/syncthing-data"

[config.services.innernet.client.insane]
enable = true

[config.services.innernet.client.insane.settings.interface]
address = "192.168.104.65/22"
privateKeyFile = "/run/agenix/wg-home"

[config.services.innernet.client.insane.settings.server]
publicKey = "Ca4OCVKasunoIVyh3vbp/HyLnrPWp7AOwEuV14PS1QY="
externalEndpoint = "65.108.2.146:51820"
internalEndpoint = "192.168.104.1:51820"

[config.users.groups.john]
gid = 1337

[config.users.users.john]
uid = 1337
shell = "nushell"
hashedPassword = "$6$RG3QgdVr6A5s524$FRVNXOYWYCNXf6cH/gV4u7g6sffffznBnbXZGHysuWVHGYPpeLfuDuXEJHK.KUrkVCfPXFTTsCLJaj2Q6ATkC1"
openssh.authorizedKeys.keys = [
  "sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIJY3QSBIiRKN8/B3nHgCBDpauQBOftphOeuF2TaBHGQSAAAABHNzaDo=",
  "sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIAwJWtQ5ZU9U0szWzJ+/GH2uvXZ15u9lL0RdcHdsXM0VAAAABHNzaDo=",
]

[config.home-manager.users.john]
profiles = [
  "users/profiles/alacritty",
  "users/profiles/chromium",
  "users/profiles/dconf",
  "users/profiles/firefox",
  "users/profiles/fish",
  "users/profiles/git",
  "users/profiles/i3status-desktop",
  "users/profiles/kanshi",
  "users/profiles/kubie",
  "users/profiles/mako",
  "users/profiles/nushell",
  "users/profiles/obs",
  "users/profiles/pueue",
  "users/profiles/qutebrowser",
  "users/profiles/rbw",
  "users/profiles/river",
  "users/profiles/rofi",
  "users/profiles/spotifyd",
  "users/profiles/spotnix",
  "users/profiles/ssh",
  "users/profiles/starship",
  "users/profiles/sway",
  "users/profiles/tmux",
  "users/profiles/waybar",
  "users/profiles/wlsunset",
]

[config.home-manager.users.john.home.file.".emacs"]
source = "${pkgs.my-emacs-config}"

[config.home-manager.users.john.programs.bat]
enable = true

[config.home-manager.users.john.programs.emacs]
enable = true
package = "${pkgs.my-emacs}"

[config.home-manager.users.john.services.emacs]
enable = true
package = "${pkgs.my-emacs}"
socketActivation.enable = true

[config.home-manager.users.john.systemd.user.services.emacs.Service]
Environment = [ "COLORTERM=truecolor" ]
LimitNOFILE = 16384

[config.home-manager.users.john.programs.rbw]
settings.device_id = "f3268147-1e9d-46da-b431-11fe011f5dfe"

[config.home-manager.users.john.programs.mbsync]
enable = true

[config.home-manager.users.john.services.mbsync]
enable = true
frequency = "*:0/5"

[config.home-manager.users.john.services.imapnotify]
enable = true

[config.home-manager.users.john.userinfo]
email = "john@insane.se"
fullName = "John Axel Eriksson"
githubUser = "johnae"
gitlabUser = "johnae"
gitIdMap."~/Development/planhat/" = "john.eriksson@planhat.com"

[config.home-manager.users.john.services.gitAutoSync.repos."~/Development/org-roam"]
repository = "git@github.com:johnae/org-roam"
sshKey = "/run/agenix/id_ed25519_roam_updater"

[config.home-manager.users.john.services.gitAutoSync.repos."~/Development/org-agenda"]
repository = "git@github.com:johnae/org-agenda"
sshKey = "/run/agenix/id_ed25519_agenda_updater"

[config.home-manager.users.john.programs.git]
extraConfig.user.signingKey = "key::sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIAwJWtQ5ZU9U0szWzJ+/GH2uvXZ15u9lL0RdcHdsXM0VAAAABHNzaDo="
extraConfig.gpg.format = "ssh"
extraConfig.commit.gpgSign = true
extraConfig.tag.forceSignAnnotated = true

[config.home-manager.users.john.accounts.email]
maildirBasePath = "Mail"

[config.home-manager.users.john.accounts.email.accounts.insane]
address = "john@insane.se"
primary = true
flavor = "gmail.com"
mbsync.enable = true
mbsync.create = "both"
mbsync.extraConfig.account.PipelineDepth = 10
passwordCommand = "${pkgs.coreutils}/bin/cat /run/agenix/mbsync-insane"
imapnotify.enable = true
imapnotify.boxes = [ "Inbox" ]
imapnotify.onNotify = "${pkgs.isync}/bin/mbsync insane"
imapnotify.onNotifyPost = "${pkgs.mu}/bin/mu index"

[config.home-manager.users.john.accounts.email.accounts.insane.mbsync.groups.insane.channels]
inbox.patterns = ["INBOX"]
inbox.extraConfig.Create = "both"
inbox.extraConfig.SyncState = "*"

all.farPattern = "[Gmail]/All Mail"
all.nearPattern = "All"
all.extraConfig.Create = "near"
all.extraConfig.SyncState = "*"

sent.farPattern = "[Gmail]/Sent Mail"
sent.nearPattern = "Sent"
sent.extraConfig.Create = "near"
sent.extraConfig.SyncState = "*"

trash.farPattern = "[Gmail]/Trash"
trash.nearPattern = "Trash"
trash.extraConfig.Create = "near"
trash.extraConfig.SyncState = "*"

drafts.farPattern = "[Gmail]/Drafts"
drafts.nearPattern = "Drafts"
drafts.extraConfig.Create = "near"
drafts.extraConfig.SyncState = "*"

[config.home-manager.users.john.accounts.email.accounts.9000]
address = "john@9000.dev"
userName = "john@9000.dev"
primary = false
imap.host = "mail.9000.dev"
mbsync.enable = true
mbsync.create = "both"
mbsync.extraConfig.account.PipelineDepth = 10
passwordCommand = "${pkgs.coreutils}/bin/cat /run/agenix/mbsync-9000"
imapnotify.enable = true
imapnotify.boxes = [ "Inbox" ]
imapnotify.onNotify = "${pkgs.isync}/bin/mbsync 9000"
imapnotify.onNotifyPost = "${pkgs.mu}/bin/mu index"

[config.home-manager.users.john.accounts.email.accounts.insane.mbsync.groups.9000.channels]
all.patterns = ["*"]
all.extraConfig.Create = "near"
all.extraConfig.SyncState = "*"
all.extraConfig.CopyArrivalDate = "yes"