system = "x86_64-linux"

[config]
publicKey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMoTdeqiDgd0BjhgDu96R+fD1s3PNmAB0UgHFet+IPhS"
syncthingDeviceID = "FB5PKN4-5KT7RPB-5JXSO2B-7BTWIG6-FEPT7FA-AZT4QIP-Z3AMM3L-OQXZPQI"

profiles = [
  "profiles/hardware/nuc",
  "profiles/default_fs",
  "profiles/hidpi",
  "profiles/k3s",
  "profiles/server",
  "profiles/state",
  "profiles/syncthing",
  "profiles/uuid_disk_crypt",
  "profiles/zram",
]

users.groups.john.gid = 1337
users.users.john.uid = 1337
users.users.john.hashedPassword = "$6$Juk1xlDWz45N5dGc$W.BxolEvo.yWR3DgqzErIdXYYCXq4TjauGN8iA/kdlpaJiPw1lvdecydfF37yfnmTFU.vtnXUVVw3QOgwcJE.0"
users.users.john.openssh.authorizedKeys.keys = [
  "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCyjMuNOFrZBi7CrTyu71X+aRKyzvTmwCEkomhB0dEhENiQ3PTGVVWBi1Ta9E9fqbqTW0HmNL5pjGV+BU8j9mSi6VxLzJVUweuwQuvqgAi0chAJVPe0FSzft9M7mJoEq5DajuSiL7dSjXpqNFDk/WCDUBE9pELw+TXvxyQpFO9KZwiYCCNRQY6dCjrPJxGwG+JzX6l900GFrgOXQ3KYGk8vzep2Qp+iuH1yTgEowUICkb/9CmZhHQXSvq2gAtoOsGTd9DTyLOeVwZFJkTL/QW0AJNRszckGtYdA3ftCUNsTLSP/VqYN9EjxcMHQe4PGjkK7VLb59DQJFyRQqvPXiUyxNloHcu/sDuiKHIk/0qDLHlVn2xc5zkvzSqoQxoXx+P4dDbje1KHLY8E96gLe2Csu0ti+qsM5KEvgYgwWwm2g3IBlaWwgAtC0UWEzIuBPrAgPd5vi+V50ITIaIk6KIV7JPOubLUXaLS5KW77pWyi9PqAGOXj+DgTWoB3QeeZh7CGhPL5fAecYN7Pw734cULZpnw10Bi/jp4Nlq1AJDk8BwLUJbzZ8aexwMf78syjkHJBBrTOAxADUE02nWBQd0w4K5tl/a3UnBYWGyX8TD44046Swl/RY/69PxFvYcVRuF4eARI6OWojs1uhoR9WkO8eGgEsuxxECwNpWxR5gjKcgJQ==",
  "sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIJY3QSBIiRKN8/B3nHgCBDpauQBOftphOeuF2TaBHGQSAAAABHNzaDo=",
  "sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIAwJWtQ5ZU9U0szWzJ+/GH2uvXZ15u9lL0RdcHdsXM0VAAAABHNzaDo=",
]

networking.defaultGateway = "192.168.20.1"
networking.interfaces.eth0.ipv4.addresses = [
  { address = "192.168.20.141", prefixLength = 24 }
]

services.syncthing.enable = true
services.syncthing.user = "john"
services.syncthing.group = "users"
services.syncthing.openDefaultPorts = true
services.syncthing.folders."/home/john/Sync".id = "sync"
services.syncthing.folders."/home/john/Sync".devices = [
  "triton",
  "eris",
  "icarus",
  "polaris",
  "titan"
]
services.syncthing.cert = "/run/agenix/syncthing-cert"
services.syncthing.key = "/run/agenix/syncthing-key"
services.syncthing.dataDir = "/home/john/.local/share/syncthing-data"

services.innernet.client.insane.enable = true
services.innernet.client.insane.settings.interface = { address = "192.168.104.68/22", privateKeyFile = "/run/agenix/wg-home" }
services.innernet.client.insane.settings.server = { publicKey = "Ca4OCVKasunoIVyh3vbp/HyLnrPWp7AOwEuV14PS1QY=", externalEndpoint = "65.108.2.146:51820", internalEndpoint = "192.168.104.1:51820" }

system.autoUpgrade = { enable = true, flake = "github:johnae/world", allowReboot = true, dates = "*:0/15", randomizedDelaySec = "5min", enableSentinel = true }

age.secrets.k3s-token.file = "secrets/k3s/token.age"
age.secrets.wg-home.file = "secrets/hyperion/wg-home.age"
age.secrets.syncthing-cert = { file = "secrets/hyperion/syncthing-cert.age", owner = "1337" }
age.secrets.syncthing-key = { file = "secrets/hyperion/syncthing-key.age", owner = "1337" }

networking.firewall.trustedInterfaces = [ "insane" ] ## trust the vpn mesh

services.k3s.role = "server"
services.k3s.settings.server = "https://192.168.104.1:6443"
services.k3s.settings.token-file = "/run/agenix/k3s-token"
services.k3s.settings.flannel-iface = "insane"
services.k3s.settings.node-ip = "192.168.104.68"
services.k3s.settings.node-external-ip = "192.168.20.141"
services.k3s.settings.with-node-id = true
services.k3s.settings.advertise-address = "192.168.104.68"
services.k3s.settings.cluster-cidr = "10.128.128.0/21"
services.k3s.settings.service-cidr = "10.129.128.0/22"
services.k3s.settings.cluster-dns = "10.129.128.10"
services.k3s.settings.kubelet-arg.max-pods = 62
services.k3s.settings.kube-controller-manager-arg.node-cidr-mask-size = 25
services.k3s.settings.kube-apiserver-arg.oidc-issuer-url = "https://dex.insane.se"
services.k3s.settings.kube-apiserver-arg.oidc-username-claim = "email"
services.k3s.settings.kube-apiserver-arg.oidc-groups-claim = "groups"
services.k3s.settings.kube-apiserver-arg.oidc-client-id = "dex-auth"
services.k3s.settings.node-label."topology.kubernetes.io/region" = "home"
services.k3s.settings.node-label."topology.kubernetes.io/zone" = "home"
services.k3s.settings.secrets-encryption = true
services.k3s.settings.tls-san = "192.168.104.100"

services.k3s.after = [ "innernet-client-insane.service" ]