system = "x86_64-linux"

[config]
publicKey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEaNfCJeVMxPC290oQxf16mrRHX+swWKlo3uhm3ZmYBK"
syncthingDeviceID = "FB5PKN4-5KT7RPB-5JXSO2B-7BTWIG6-FEPT7FA-AZT4QIP-Z3AMM3L-OQXZPQI"
profiles = [
  "profiles/hardware/nuc",
  "profiles/default_fs",
  "profiles/server",
  "profiles/state",
  "profiles/syncthing",
  "profiles/tailscale",
  "profiles/uuid_disk_crypt",
  "profiles/zram",
]

[config.system.autoUpgrade]
enable = true
flake = "github:johnae/world"
allowReboot = true
dates = "*:0/15"
randomizedDelaySec = "5min"
enableSentinel = true

[config.users.groups.john]
gid = 1337

[config.users.users.john]
uid = 1337
hashedPassword = "$6$Juk1xlDWz45N5dGc$W.BxolEvo.yWR3DgqzErIdXYYCXq4TjauGN8iA/kdlpaJiPw1lvdecydfF37yfnmTFU.vtnXUVVw3QOgwcJE.0"
openssh.authorizedKeys.keys = [
  "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCyjMuNOFrZBi7CrTyu71X+aRKyzvTmwCEkomhB0dEhENiQ3PTGVVWBi1Ta9E9fqbqTW0HmNL5pjGV+BU8j9mSi6VxLzJVUweuwQuvqgAi0chAJVPe0FSzft9M7mJoEq5DajuSiL7dSjXpqNFDk/WCDUBE9pELw+TXvxyQpFO9KZwiYCCNRQY6dCjrPJxGwG+JzX6l900GFrgOXQ3KYGk8vzep2Qp+iuH1yTgEowUICkb/9CmZhHQXSvq2gAtoOsGTd9DTyLOeVwZFJkTL/QW0AJNRszckGtYdA3ftCUNsTLSP/VqYN9EjxcMHQe4PGjkK7VLb59DQJFyRQqvPXiUyxNloHcu/sDuiKHIk/0qDLHlVn2xc5zkvzSqoQxoXx+P4dDbje1KHLY8E96gLe2Csu0ti+qsM5KEvgYgwWwm2g3IBlaWwgAtC0UWEzIuBPrAgPd5vi+V50ITIaIk6KIV7JPOubLUXaLS5KW77pWyi9PqAGOXj+DgTWoB3QeeZh7CGhPL5fAecYN7Pw734cULZpnw10Bi/jp4Nlq1AJDk8BwLUJbzZ8aexwMf78syjkHJBBrTOAxADUE02nWBQd0w4K5tl/a3UnBYWGyX8TD44046Swl/RY/69PxFvYcVRuF4eARI6OWojs1uhoR9WkO8eGgEsuxxECwNpWxR5gjKcgJQ==",
  "sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIJY3QSBIiRKN8/B3nHgCBDpauQBOftphOeuF2TaBHGQSAAAABHNzaDo=",
  "sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIAwJWtQ5ZU9U0szWzJ+/GH2uvXZ15u9lL0RdcHdsXM0VAAAABHNzaDo=",
]

[config.networking]
defaultGateway = "192.168.20.1"

[config.networking.firewall]
trustedInterfaces = [ "insane" ] ## trust the vpn mesh

[[config.networking.interfaces.eth0.ipv4.addresses]]
address = "192.168.20.141"
prefixLength = 24

[config.services.syncthing]
enable = true
user = "john"
group = "users"
openDefaultPorts = true
cert = "/run/agenix/syncthing-cert"
key = "/run/agenix/syncthing-key"
dataDir = "/home/john/.local/share/syncthing-data"

[config.services.syncthing.settings]
folders."/home/john/Sync".id = "sync"
folders."/home/john/Sync".devices = [
  "antares",
  "eris",
  "atlas",
  "icarus",
  "polaris",
  "titan",
  "sirius",
  "vela",
]

[config.age.secrets]
wg-home.file = "secrets/hyperion/wg-home.age"
syncthing-cert = { file = "secrets/hyperion/syncthing-cert.age", owner = "1337" }
syncthing-key = { file = "secrets/hyperion/syncthing-key.age", owner = "1337" }
tailscale-auth = { file = "secrets/tailscale-auth.age" }
ts-gh-9k = { file = "secrets/ts-gh-9k.age", owner = "1337" }

[config.services.tailscale.auth]
enable = true
args.advertise-tags = ["tag:server"]
args.ssh = true
args.accept-routes = false
args.accept-dns = false
args.auth-key = "file:/var/run/agenix/ts-gh-9k"