system = "x86_64-linux"

[config]
publicKey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH94CfBpOmh++ESfKq5oY1xeRxtOexFBl8AOxyPYBk6U"

profiles = [
  "profiles/hardware/hcloud",
  "profiles/hcloud-k3s-core",
  "profiles/tailscale",
]

[config.users.users.root]
extraGroups = []
openssh.authorizedKeys.keys = [
  "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCyjMuNOFrZBi7CrTyu71X+aRKyzvTmwCEkomhB0dEhENiQ3PTGVVWBi1Ta9E9fqbqTW0HmNL5pjGV+BU8j9mSi6VxLzJVUweuwQuvqgAi0chAJVPe0FSzft9M7mJoEq5DajuSiL7dSjXpqNFDk/WCDUBE9pELw+TXvxyQpFO9KZwiYCCNRQY6dCjrPJxGwG+JzX6l900GFrgOXQ3KYGk8vzep2Qp+iuH1yTgEowUICkb/9CmZhHQXSvq2gAtoOsGTd9DTyLOeVwZFJkTL/QW0AJNRszckGtYdA3ftCUNsTLSP/VqYN9EjxcMHQe4PGjkK7VLb59DQJFyRQqvPXiUyxNloHcu/sDuiKHIk/0qDLHlVn2xc5zkvzSqoQxoXx+P4dDbje1KHLY8E96gLe2Csu0ti+qsM5KEvgYgwWwm2g3IBlaWwgAtC0UWEzIuBPrAgPd5vi+V50ITIaIk6KIV7JPOubLUXaLS5KW77pWyi9PqAGOXj+DgTWoB3QeeZh7CGhPL5fAecYN7Pw734cULZpnw10Bi/jp4Nlq1AJDk8BwLUJbzZ8aexwMf78syjkHJBBrTOAxADUE02nWBQd0w4K5tl/a3UnBYWGyX8TD44046Swl/RY/69PxFvYcVRuF4eARI6OWojs1uhoR9WkO8eGgEsuxxECwNpWxR5gjKcgJQ==",
  "sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIJY3QSBIiRKN8/B3nHgCBDpauQBOftphOeuF2TaBHGQSAAAABHNzaDo=",
  "sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIAwJWtQ5ZU9U0szWzJ+/GH2uvXZ15u9lL0RdcHdsXM0VAAAABHNzaDo=",
]

[config.age.secrets]
k3s-token.file = "secrets/k3s/token.age"
ts-9k = { file = "secrets/ts-9k.age", owner = "1337" }

[config.services.tailscale.auth]
enable = true
args.advertise-tags = ["tag:server"]
args.ssh = true
args.accept-routes = false ## with this on, it causes issues in k3s when network runs on top of tailscale
args.accept-dns = true
args.advertise-exit-node = true
args.auth-key = "file:/var/run/agenix/ts-9k"

[config.services.k3s]
enable = true
role = "agent"
after = [ "tailscale-auth.service" ]

[config.services.k3s.settings]
server = "https://k8s-master-0.taileb01.ts.net:6443"
token-file = "/run/agenix/k3s-token"
flannel-iface = "tailscale0"
node-ip = "$(get-iface-ip tailscale0)"
node-external-ip = "$(get-iface-ip eth0)"
with-node-id = true
kubelet-arg.max-pods = 62
node-label."svccontroller.k3s.cattle.io/enablelb" = "true"
node-label."topology.kubernetes.io/region" = "hetzner"
node-label."topology.kubernetes.io/zone" = "hetzner-fi"
