system = "x86_64-linux"

[config]
publicKey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILOeY+TshjtBK5VQu4ZJVJ0ol1PsZxLvIy+YNCOtfZmd"
syncthingDeviceID = "5RMZCHO-M3OA4UH-3PMKBWD-IVJGW4Q-VZBME6O-OCSPMK4-7YOVDAM-QOEDOQC"

profiles = [
  "profiles/hardware/ax41",
  "profiles/acme",
  "profiles/default_fs",
  "profiles/home-manager",
  "profiles/jellyfin",
  "profiles/server",
  "profiles/state",
  "profiles/syncthing",
  "profiles/tailscale",
  "profiles/zram",
]

#[config.btrfs]
#disks = [ "/dev/nvme0n1", "/dev/nvme1n1" ]

[config.programs.mosh]
enable = true

[config.boot.binfmt]
emulatedSystems = [ "aarch64-linux" ]

[config.system.autoUpgrade]
enable = true
flake = "github:johnae/world"
allowReboot = true
dates = "*:0/15"
randomizedDelaySec = "5min"
enableSentinel = true

[config.boot]
kernelParams = [
  "ip=65.108.2.146::65.108.2.129:255.255.255.192:polaris:eth0:none",
]

[config.boot.initrd]
availableKernelModules = [
  "r8169",
  "nvme",
  "ahci",
  "usbhid",
]

[config.boot.initrd.network]
enable = true
postCommands = "echo 'cryptsetup-askpass' >> /root/.profile"

[config.boot.initrd.network.ssh]
enable = true
port = 2222
## This isn't so nice. Have to copy the file to /keep/secrets and keep it there.
hostKeys = [
  "/keep/secrets/initrd_ed25519_key",
]
authorizedKeys = [
  "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCyjMuNOFrZBi7CrTyu71X+aRKyzvTmwCEkomhB0dEhENiQ3PTGVVWBi1Ta9E9fqbqTW0HmNL5pjGV+BU8j9mSi6VxLzJVUweuwQuvqgAi0chAJVPe0FSzft9M7mJoEq5DajuSiL7dSjXpqNFDk/WCDUBE9pELw+TXvxyQpFO9KZwiYCCNRQY6dCjrPJxGwG+JzX6l900GFrgOXQ3KYGk8vzep2Qp+iuH1yTgEowUICkb/9CmZhHQXSvq2gAtoOsGTd9DTyLOeVwZFJkTL/QW0AJNRszckGtYdA3ftCUNsTLSP/VqYN9EjxcMHQe4PGjkK7VLb59DQJFyRQqvPXiUyxNloHcu/sDuiKHIk/0qDLHlVn2xc5zkvzSqoQxoXx+P4dDbje1KHLY8E96gLe2Csu0ti+qsM5KEvgYgwWwm2g3IBlaWwgAtC0UWEzIuBPrAgPd5vi+V50ITIaIk6KIV7JPOubLUXaLS5KW77pWyi9PqAGOXj+DgTWoB3QeeZh7CGhPL5fAecYN7Pw734cULZpnw10Bi/jp4Nlq1AJDk8BwLUJbzZ8aexwMf78syjkHJBBrTOAxADUE02nWBQd0w4K5tl/a3UnBYWGyX8TD44046Swl/RY/69PxFvYcVRuF4eARI6OWojs1uhoR9WkO8eGgEsuxxECwNpWxR5gjKcgJQ==",
  "sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIJY3QSBIiRKN8/B3nHgCBDpauQBOftphOeuF2TaBHGQSAAAABHNzaDo=",
  "sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIAwJWtQ5ZU9U0szWzJ+/GH2uvXZ15u9lL0RdcHdsXM0VAAAABHNzaDo=",
  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK+trOinD68RD1efI6p05HeaNA0SjzeRnUvpf22+jsq+",
]

[config.users.groups.john]
gid = 1337

[config.users.users.john]
uid = 1337
shell = "nushell"
hashedPassword = "$6$MY8KAtdXlQP5.$TEZbPueD71fYUGviybTjFWCD5s1eWmr9FK9WtoLFKFy3yfLu18KPJ2wAbK8ZVJDo52hsc0vGa4LKYbzb.pwPk0"
openssh.authorizedKeys.keys = [
  "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCyjMuNOFrZBi7CrTyu71X+aRKyzvTmwCEkomhB0dEhENiQ3PTGVVWBi1Ta9E9fqbqTW0HmNL5pjGV+BU8j9mSi6VxLzJVUweuwQuvqgAi0chAJVPe0FSzft9M7mJoEq5DajuSiL7dSjXpqNFDk/WCDUBE9pELw+TXvxyQpFO9KZwiYCCNRQY6dCjrPJxGwG+JzX6l900GFrgOXQ3KYGk8vzep2Qp+iuH1yTgEowUICkb/9CmZhHQXSvq2gAtoOsGTd9DTyLOeVwZFJkTL/QW0AJNRszckGtYdA3ftCUNsTLSP/VqYN9EjxcMHQe4PGjkK7VLb59DQJFyRQqvPXiUyxNloHcu/sDuiKHIk/0qDLHlVn2xc5zkvzSqoQxoXx+P4dDbje1KHLY8E96gLe2Csu0ti+qsM5KEvgYgwWwm2g3IBlaWwgAtC0UWEzIuBPrAgPd5vi+V50ITIaIk6KIV7JPOubLUXaLS5KW77pWyi9PqAGOXj+DgTWoB3QeeZh7CGhPL5fAecYN7Pw734cULZpnw10Bi/jp4Nlq1AJDk8BwLUJbzZ8aexwMf78syjkHJBBrTOAxADUE02nWBQd0w4K5tl/a3UnBYWGyX8TD44046Swl/RY/69PxFvYcVRuF4eARI6OWojs1uhoR9WkO8eGgEsuxxECwNpWxR5gjKcgJQ==",
  "sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIJY3QSBIiRKN8/B3nHgCBDpauQBOftphOeuF2TaBHGQSAAAABHNzaDo=",
  "sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIAwJWtQ5ZU9U0szWzJ+/GH2uvXZ15u9lL0RdcHdsXM0VAAAABHNzaDo=",
]

[config.services.nginx]
enable = true
recommendedTlsSettings = true
recommendedProxySettings = true
recommendedGzipSettings = true
recommendedOptimisation = true
clientMaxBodySize = "300m"

[config.services.dex]
enable = true
environmentFile = "/var/run/agenix/dex-environment"

[config.services.dex.settings]
issuer = "https://id.9000.dev"
oauth2.responseTypes = [ "code", "token", "id_token" ]
oauth2.skipApprovalScreen = true
storage.type = "sqlite3"
storage.config.file = "/var/lib/dex/dex.db"
web.http = "127.0.0.1:5556"

[[config.services.dex.settings.connectors]]
id = "github"
name = "GitHub"
type = "github"
config.clientID = "$GITHUB_CLIENT_ID"
config.clientSecret = "$GITHUB_CLIENT_SECRET"
config.orgs = [ { name = "9k-dev", teams = [ "Admins", "Viewers" ] } ]
config.redirectURI = "https://id.9000.dev/callback"

[[config.services.dex.settings.staticClients]]
id = "dex-auth"
name = "dex-auth"
secretEnv = "DEX_STATIC_CLIENT_SECRET"
redirectURIs = [ "http://localhost:8000", "http://localhost:18000", "https://johnae.cloudflareaccess.com/cdn-cgi/access/callback", "https://tailscale.9000.dev/oidc/callback" ]

[config.systemd.services.dex.serviceConfig]
BindPaths = [ "/var/lib/dex" ]

[config.services.nginx.virtualHosts."id.9000.dev"]
forceSSL = true
enableACME = true
locations."/".proxyPass = "http://localhost:5556"
locations."/".proxyWebsockets = true

[config.services.tailscale.auth]
enable = true
args.advertise-tags = ["tag:server"]
args.ssh = true
args.accept-routes = false
args.accept-dns = false
args.advertise-exit-node = true
args.auth-key = "file:/var/run/agenix/ts-gh-9k"
args.advertise-routes = "10.128.128.0/21,10.129.128.0/22"

[config.services.syncthing]
enable = true
user = "john"
group = "users"
openDefaultPorts = true
cert = "/run/agenix/syncthing-cert"
key = "/run/agenix/syncthing-key"
dataDir = "/home/john/.local/share/syncthing-data"

[config.services.syncthing.settings]
devices.s23ultra.id = "WIEQUVJ-5TNGRPN-YD4E47D-WEXXBZO-2AGHFQZ-2K4DDRB-DFSD2UZ-34OCBQ4"
devices.s8plus.id = "EI6DXMZ-3CMM3R3-LNJPFIF-CTXDVAG-2SXLOCY-4NEEZ3K-CYJBXU6-6W44TAV"
folders."/home/john/Sync".id = "sync"
folders."/home/john/Sync".devices = [
  "antares",
  "eris",
  "atlas",
  "icarus",
  "titan",
  "hyperion",
  "sirius",
  "vela",
  "s23ultra",
  "s8plus"
]

[config.networking]
defaultGateway = "65.108.2.129"
defaultGateway6 = { address = "fe80::1", interface = "eth0" }

[[config.networking.interfaces.eth0.ipv4.addresses]]
address = "65.108.2.146"
prefixLength = 26

[[config.networking.interfaces.eth0.ipv6.addresses]]
address = "2a01:4f9:6a:51ed::2"
prefixLength = 64

[config.networking.private-wireguard]
enable = true
ips = [
  "10.65.167.230/32",
  "fc00:bbbb:bbbb:bb01::2:a7e5/128"
]
privateKeyFile = "/run/agenix/wg-net"

[[config.networking.private-wireguard.peers]]
allowedIPs = [ "0.0.0.0/0", "::0/0" ]
endpoint = "185.65.135.70:51820"
publicKey = "615mnBGkvjZnD/vRbyL/6da7YhtctfB+jimN+wfV724="

[config.networking.firewall]
trustedInterfaces = [ "insane" ] ## trust the vpn mesh
allowedUDPPorts = [ 5349, 3478 ]
allowedTCPPorts = [ 5349, 3478, 80, 443 ]
allowedUDPPortRanges = [ { from = 49160, to = 49200 } ]

[config.age.secrets]
wg-home.file = "secrets/polaris/wg-home.age"
wg-net.file = "secrets/polaris/wg-net.age"
syncthing-cert = { file = "secrets/polaris/syncthing-cert.age", owner = "1337" }
syncthing-key = { file = "secrets/polaris/syncthing-key.age", owner = "1337" }
mailserver-john = { file = "secrets/mail/mailserver-john.age"}
cloudflare-env = { file = "secrets/cloudflare-env.age" }
#auth-9000-headscale = { file = "secrets/auth-9000.age", owner = "headscale", group = "headscale" }
dex-environment = { file = "secrets/dex-environment.age" }
tailscale-auth = { file = "secrets/tailscale-auth.age" }
ts-gh-9k = { file = "secrets/ts-gh-9k.age", owner = "1337" }

mbsync-insane = { file = "secrets/mbsync-insane.age", owner = "1337" }
mbsync-9000 = { file = "secrets/mbsync-9000.age", owner = "1337" }
authinfo = { file = "secrets/authinfo.age", owner = "1337", path = "/home/john/.authinfo" }

[config.environment.state."/keep"]
directories = [
  "/var/lib/dex",
  "/var/lib/headscale",
  "/var/lib/jellyfin",
  "/var/lib/media",
]

[config.home-manager.users.john]
profiles = [
  "users/profiles/fish",
  "users/profiles/git",
  "users/profiles/kubie",
  "users/profiles/nushell",
  "users/profiles/pueue",
  "users/profiles/rbw",
  "users/profiles/ssh",
  "users/profiles/starship",
  "users/profiles/tmux",
]

[config.home-manager.users.john.programs.bat]
enable = true

[config.home-manager.users.john.programs.emacs]
enable = true
package = "${pkgs.my-emacs}"

[config.home-manager.users.john.services.emacs]
enable = true
package = "${pkgs.my-emacs}"
socketActivation.enable = true

[config.home-manager.users.john.systemd.user.services.emacs.Service]
Environment = [ "COLORTERM=truecolor" ]
LimitNOFILE = 16384

[config.home-manager.users.john.userinfo]
email = "john@insane.se"
fullName = "John Axel Eriksson"
githubUser = "johnae"
gitlabUser = "johnae"

[config.programs.dconf]
enable = true

[config.home-manager.users.john.programs.mbsync]
enable = true

[config.home-manager.users.john.services.mbsync]
enable = true
frequency = "*:0/5"

[config.home-manager.users.john.services.imapnotify]
enable = true

[config.home-manager.users.john.services.gitAutoSync.repos."~/Development/org-roam"]
repository = "git@github.com:johnae/org-roam"
sshKey = "/run/agenix/id_ed25519_roam_updater"

[config.home-manager.users.john.services.gitAutoSync.repos."~/Development/org-agenda"]
repository = "git@github.com:johnae/org-agenda"
sshKey = "/run/agenix/id_ed25519_agenda_updater"

[config.home-manager.users.john.accounts.email]
maildirBasePath = "Mail"

[config.home-manager.users.john.accounts.email.accounts.insane]
address = "john@insane.se"
primary = true
flavor = "gmail.com"
mbsync.enable = true
mbsync.create = "both"
mbsync.extraConfig.account.PipelineDepth = 10
passwordCommand = "${pkgs.coreutils}/bin/cat /run/agenix/mbsync-insane"
imapnotify.enable = true
imapnotify.boxes = [ "Inbox" ]
imapnotify.onNotify = "${pkgs.isync}/bin/mbsync insane"
imapnotify.onNotifyPost = "${pkgs.mu}/bin/mu index"

[config.home-manager.users.john.accounts.email.accounts.insane.mbsync.groups.gmail.channels]
inbox.patterns = ["INBOX"]
inbox.extraConfig.Create = "both"
inbox.extraConfig.SyncState = "*"

all.farPattern = "[Gmail]/All Mail"
all.nearPattern = "All"
all.extraConfig.Create = "near"
all.extraConfig.SyncState = "*"

sent.farPattern = "[Gmail]/Sent Mail"
sent.nearPattern = "Sent"
sent.extraConfig.Create = "near"
sent.extraConfig.SyncState = "*"

trash.farPattern = "[Gmail]/Trash"
trash.nearPattern = "Trash"
trash.extraConfig.Create = "near"
trash.extraConfig.SyncState = "*"

drafts.farPattern = "[Gmail]/Drafts"
drafts.nearPattern = "Drafts"
drafts.extraConfig.Create = "near"
drafts.extraConfig.SyncState = "*"

[config.home-manager.users.john.accounts.email.accounts.9000]
address = "john@9000.dev"
userName = "john@9000.dev"
primary = false
imap.host = "mail.9000.dev"
mbsync.enable = true
mbsync.create = "both"
mbsync.extraConfig.account.PipelineDepth = 10
passwordCommand = "${pkgs.coreutils}/bin/cat /run/agenix/mbsync-9000"
imapnotify.enable = true
imapnotify.boxes = [ "Inbox" ]
imapnotify.onNotify = "${pkgs.isync}/bin/mbsync 9000"
imapnotify.onNotifyPost = "${pkgs.mu}/bin/mu index"

[config.home-manager.users.john.accounts.email.accounts.insane.mbsync.groups.9000.channels]
all.patterns = ["*"]
all.extraConfig.Create = "near"
all.extraConfig.SyncState = "*"
all.extraConfig.CopyArrivalDate = "yes"