[devshell]
name = "packaging"

motd = """
{bold}{106}Packaging{reset}

These are the additional packages I want to make available to my machines. Most of them exist in nixpkgs already but
I like to keep these very up-to-date.

$(type -p menu &>/dev/null && menu)
"""

## You may add additional packages here. Please use "nix search nixpkgs some-search-string" to find packages.
packages = [
  "world-updaters",
]

[[commands]]
package = "world-updaters"
name = "update-cargo-vendor-sha"
help = "update the cargo vendor sha of a rust package"

[[commands]]
package = "world-updaters"
name = "update-all-cargo-vendor-shas"
help = "update all cargo vendor shas of all rust packages"

[[commands]]
package = "world-updaters"
name = "update-fixed-output-derivation-sha"
help = "update the fixed output derivation sha of a package"

[[commands]]
package = "world-updaters"
name = "update-all-fixed-output-derivation-shas"
help = "update all fixed output derivation shas in all such packages"