name: Hcloud Cost Mgmt

on:
  workflow_dispatch: {}
  schedule:
  - cron: '0 23 * * *'

jobs:
  cost-mgmt:
    runs-on: ubuntu-latest
    steps:
    - uses: hetznercloud/setup-hcloud@v1
    - run: |
        for S in $(hcloud server list -l "tfstate=dev" -o json | jq -r  '.[].name'); do
          hcloud server shutdown "$S"
          sleep 30
          hcloud server delete "$S"
        done
      env:
        HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
