name: Hcloud Cost Mgmt

on:
  workflow_dispatch: {}
  schedule:
  - cron: '0 23 * * *'

jobs:
  cost-mgmt:
    runs-on: ubuntu-latest
    steps:
    - uses: hetznercloud/setup-hcloud@v1
    - run: |
        hcloud server delete hcloud-dev || true
      env:
        HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
